// Generated by CoffeeScript 1.9.0
HTMLWidgets.widget({
  name: "iplot",
  type: "output",
  initialize: function(el, width, height) {
    return d3.select(el).append("svg").attr("width", width).attr("height", height).attr("class", "testjs");
  },
  renderValue: function(el, x) {
    var axispos, chartOpts, data, height, margin, mychart, nxticks, nyticks, pointcolor, pointsize, pointstroke, rectcolor, rotate_ylab, svg, title, titlepos, width, xNA, xlab, xlim, xticks, yNA, ylab, ylim, yticks, _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref14, _ref15, _ref16, _ref17, _ref18, _ref19, _ref2, _ref20, _ref21, _ref22, _ref23, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
    data = x.data;
    chartOpts = x.chartOpts;
    svg = d3.select(el).select("svg");
    chartOpts = (_ref = x.chartOpts) != null ? _ref : [];
    chartOpts.width = (_ref1 = chartOpts != null ? chartOpts.width : void 0) != null ? _ref1 : svg.attr("width");
    chartOpts.height = (_ref2 = chartOpts != null ? chartOpts.height : void 0) != null ? _ref2 : svg.attr("height");
    svg.attr("width", chartOpts.width);
    svg.attr("height", chartOpts.height);
    height = (_ref3 = chartOpts != null ? chartOpts.height : void 0) != null ? _ref3 : 500;
    width = (_ref4 = chartOpts != null ? chartOpts.width : void 0) != null ? _ref4 : 800;
    title = (_ref5 = chartOpts != null ? chartOpts.title : void 0) != null ? _ref5 : "";
    margin = (_ref6 = chartOpts != null ? chartOpts.margin : void 0) != null ? _ref6 : {
      left: 60,
      top: 40,
      right: 40,
      bottom: 40,
      inner: 5
    };
    xlab = (_ref7 = chartOpts != null ? chartOpts.xlab : void 0) != null ? _ref7 : "X";
    ylab = (_ref8 = chartOpts != null ? chartOpts.ylab : void 0) != null ? _ref8 : "Y";
    axispos = (_ref9 = chartOpts != null ? chartOpts.axispos : void 0) != null ? _ref9 : {
      xtitle: 25,
      ytitle: 30,
      xlabel: 5,
      ylabel: 5
    };
    titlepos = (_ref10 = chartOpts != null ? chartOpts.titlepos : void 0) != null ? _ref10 : 20;
    xlim = (_ref11 = chartOpts != null ? chartOpts.xlim : void 0) != null ? _ref11 : null;
    xticks = (_ref12 = chartOpts != null ? chartOpts.xticks : void 0) != null ? _ref12 : null;
    nxticks = (_ref13 = chartOpts != null ? chartOpts.nxticks : void 0) != null ? _ref13 : 5;
    ylim = (_ref14 = chartOpts != null ? chartOpts.ylim : void 0) != null ? _ref14 : null;
    yticks = (_ref15 = chartOpts != null ? chartOpts.yticks : void 0) != null ? _ref15 : null;
    nyticks = (_ref16 = chartOpts != null ? chartOpts.nyticks : void 0) != null ? _ref16 : 5;
    rectcolor = (_ref17 = chartOpts != null ? chartOpts.rectcolor : void 0) != null ? _ref17 : "#E6E6E6";
    pointcolor = (_ref18 = chartOpts != null ? chartOpts.pointcolor : void 0) != null ? _ref18 : null;
    pointsize = (_ref19 = chartOpts != null ? chartOpts.pointsize : void 0) != null ? _ref19 : 3;
    pointstroke = (_ref20 = chartOpts != null ? chartOpts.pointstroke : void 0) != null ? _ref20 : "black";
    rotate_ylab = (_ref21 = chartOpts != null ? chartOpts.rotate_ylab : void 0) != null ? _ref21 : null;
    xNA = (_ref22 = chartOpts != null ? chartOpts.xNA : void 0) != null ? _ref22 : {
      handle: true,
      force: false,
      width: 15,
      gap: 10
    };
    yNA = (_ref23 = chartOpts != null ? chartOpts.yNA : void 0) != null ? _ref23 : {
      handle: true,
      force: false,
      width: 15,
      gap: 10
    };
    mychart = scatterplot().height(height - margin.top - margin.bottom).width(width - margin.left - margin.right).margin(margin).axispos(axispos).titlepos(titlepos).xlab(xlab).ylab(ylab).title(title).ylim(ylim).xlim(xlim).xticks(xticks).nxticks(nxticks).yticks(yticks).nyticks(nyticks).rectcolor(rectcolor).pointcolor(pointcolor).pointsize(pointsize).pointstroke(pointstroke).rotate_ylab(rotate_ylab).xNA(xNA).yNA(yNA).xvar('x').yvar('y').dataByInd(false);
    d3.select(el).select("svg").datum({
      data: {
        x: data.x,
        y: data.y
      },
      group: data.group,
      indID: data.indID
    }).call(mychart);
    return mychart.pointsSelect().on("mouseover", function(d) {
      return d3.select(this).attr("r", pointsize * 2);
    }).on("mouseout", function(d) {
      return d3.select(this).attr("r", pointsize);
    });
  },
  resize: function(el, width, height) {
    return d3.select(el).select("svg").attr("width", width).attr("height", height);
  }
});
